#define PLATFORM_WINDOWS	1
#define PLATFORM_MAC		2
#define PLATFORM_UNIX		3

#if defined(_WIN32)
	#define PLATFORM PLATFORM_WINDOWS
#elif defined(__APPLE__)
	#define PLATFORM PLATFORM_MAC
#else
	#define PLATFORM PLATFORM_UNIX
#endif

#if PLATFORM == PLATFORM_WINDOWS
	#include <curses.h>
#elif PLATFORM == PLATFORM_MAC || PLATFORM == PLATFORM_UNIX
	#include <ncurses.h>
#endif

#define COLOR_WHITE_ON_BLACK	1
#define COLOR_BLACK_ON_WHITE	2
#define COLOR_RED_ON_BLACK		3
#define COLOR_BLUE_ON_BLACK		4
#define COLOR_GREEN_ON_BLACK	5
#define COLOR_BLACK_ON_RED		6
#define COLOR_MAGENTA_ON_BLACK	7
#define COLOR_CYAN_ON_BLACK		8
#define COLOR_WHITE_ON_RED		9

#define COLOR_YELLOW_ON_BLACK	12